name: Auto Trade Bot

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 8AM UTC
  workflow_dispatch:

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          KRAKEN_API_KEY: ${{ secrets.KRAKEN_API_KEY }}
          KRAKEN_SECRET: ${{ secrets.KRAKEN_SECRET }}
        run: bash run.sh
